config/routes.rb
Rails.application.routes.draw do
  get 'customers/missing_email', to: 'customers#missing_email', as: 'no_email'

  get 'customers/alphabetized', to: 'customers#alphabetized', as: 'alphabetical'

  root 'customers#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord

  belongs_to :province

  validates :full_name, :phone_number, presence: true
end

app/models/province.rb
class Province < ApplicationRecord

  has_many :customer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  def index
    @customers = Customer.order(:full_name)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  def missing_email
    @customer_missing_email = Customer.where(email_address: '')
  end
  def alphabetized
    @customer = Customer.order(:full_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/common/_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to 'All Customers', root_path %></li>
      <li><%= link_to 'Alphabetical Customers', alphabetical_path %></li>
      <li><%= link_to 'Customers with no email', no_email_path %></li>
    </ul>
  </nav>
</header>

app/views/customers/_customer.html.erb
<div class="customer">
  <h1><%= customer.full_name %></h1>
  <%= image_tag customer.image %>
  <% if customer.province.nil? %>
    <p><strong>Province:</strong> None</p>
  <% else %>
    <p><strong>Province:</strong> <%= customer.province.name %></p>
  <% end %>
  <p><%= customer.phone_number %></p>
  <p><%= customer.email_address %></p>
</div>

app/views/customers/alphabetized.html.erb
<h1>All Customers ordered by their name</h1>

  <%= render partial: 'customer', collection: @customer, as: 'customer' %>

app/views/customers/index.html.erb
<h1>All Customers</h1>

  <%= render partial: 'customer', collection: @customers %>

app/views/customers/missing_email.html.erb
<h1>All Customers who are missing an email address</h1>

  <%= render partial: 'customer', collection: @customer_missing_email, as: 'customer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UltimateChallenge6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/header' %>
    <%= yield %>
  </body>
</html>